### ISSUE TITLE
Search field too big on small displays

### ISSUE THREAD

**Issue by digitalcosmos** [DataTables/Plugins#110]
The search field overflows out of the DataTables container on very small resolutions (<400px)
The culprit seems to be a hardcoded width:

``` css
div.dataTables_filter input {
     width: 16em;
}
```

Edit: I'm using the Bootstrap 3 plugin, the above code is from dataTables.bootstrap.css
