### ISSUE TITLE
dataTables.bootstrap.css redifines table header padding

### ISSUE THREAD

**Issue by jm01alternet** [DataTables/Plugins#138]
in Plugins/integration/bootstrap/3/dataTables.bootstrap.css I found that it redifines the table header padding with

```css
table.dataTable thead > tr > th {
  padding-left: 18px;
  padding-right: 18px;
}
```

and that causes problems for example if I want to use a condensed bootstrap table (eg. `<table class="table table-condensed">`).

Removing the declaration has the effect that the header row left and right padding returns to the default bootstrap 8px (which imho look better)

Thanks
