### ISSUE TITLE
bootstrap plugin with RTL pages

### ISSUE THREAD

**Issue by fisharebest** [DataTables/Plugins#177]
There are various problems with right-to-left pages (arabic, hebrew, etc.), all caused by explicit left / right attributes in the CSS.  For example,

alignment/margins of the elements in the `thead` and `tfoot`
left-hand column has no right-hand border

A common fix for these problems is to add an RTL for each rule that contains a `left` or `right` attribute.  e.g.

```css
.foo {
  text-align: left;
  margin-right: 10px;
}

[dir=rtl] .foo {
  text-align: right;
  margin-right: inherit;
  margin-left: 10px;
}
```

Of course, the majority of sites are LTR only, and no doubt people will complain of unncessary bloat.

Are you interested in RTL issues?  I want to check before I spend time creating a PR.
