### ISSUE TITLE
SearchPane Style Conflicts with Bootstrap Style

### ISSUE THREAD

**Issue by ChrisDrozdowski** [DataTables/Plugins#370]
When SearchPane is used in combination with Bootstrap (at least BS3- I didn't test BS4), items in the panes render very poorly. Font face, color, weight, are all wrong, especially font color making the items not viewable.

Here is an example: https://jsfiddle.net/2ktryhzc/

This stems from the fact that "label" is used as a class name for the items in the pane. BS also has a "label" class and thus the issue arises.

Maybe another class name should be used for items in the panel.

**Comment by DataTables** [comment]
Its coming from this:

```css
.label {
     ...
    color: #fff;
```

In Bootstrap using:

```css
div.dt-searchPanes span.label {
  color: #111;
  text-align: left;
  font-weight: normal;
}
```

Will workaround it until I get complete integration with all of the styling libraries for DataTables working for this code: https://jsfiddle.net/2ktryhzc/6/ .
